In [10]:
import sys
from pathlib import Path

sys.path.append(str(Path("..")))

from scripts.utils import load_raw_file

## Wheather Data

In [11]:
df_weather = load_raw_file("newark_airport_2016.csv")

In [12]:
df_weather.shape

(366, 16)

In [13]:
df_weather.head()

,STATION,NAME,DATE,AWND,PGTM,PRCP,SNOW,SNWD,TAVG,TMAX,TMIN,TSUN,WDF2,WDF5,WSF2,WSF5
0,USW00014734,"NEWARK LIBERTY INTERNATIONAL AIRPORT, NJ US",2016-01-01,12.75,NaN,0.0,0.0,0.0,41,43,34,NaN,270,280.0,25.9,35.1
1,USW00014734,"NEWARK LIBERTY INTERNATIONAL AIRPORT, NJ US",2016-01-02,9.40,NaN,0.0,0.0,0.0,36,42,30,NaN,260,260.0,21.0,25.1
2,USW00014734,"NEWARK LIBERTY INTERNATIONAL AIRPORT, NJ US",2016-01-03,10.29,NaN,0.0,0.0,0.0,37,47,28,NaN,270,250.0,23.9,30.0
3,USW00014734,"NEWARK LIBERTY INTERNATIONAL AIRPORT, NJ US",2016-01-04,17.22,NaN,0.0,0.0,0.0,32,35,14,NaN,330,330.0,25.9,33.1
4,USW00014734,"NEWARK LIBERTY INTERNATIONAL AIRPORT, NJ US",2016-01-05,9.84,NaN,0.0,0.0,0.0,19,31,10,NaN,360,350.0,25.1,31.1

In [14]:
df_weather.dtypes

STATION     object
NAME        object
DATE        object
AWND       float64
PGTM       float64
PRCP       float64
SNOW       float64
SNWD       float64
TAVG         int64
TMAX         int64
TMIN         int64
TSUN       float64
WDF2         int64
WDF5       float64
WSF2       float64
WSF5       float64
dtype: object

In [15]:
(100 * df_weather.isna().sum() / df_weather.shape[0])

STATION      0.000000
NAME         0.000000
DATE         0.000000
AWND         0.000000
PGTM       100.000000
PRCP         0.000000
SNOW         0.000000
SNWD         0.000000
TAVG         0.000000
TMAX         0.000000
TMIN         0.000000
TSUN       100.000000
WDF2         0.000000
WDF5         0.546448
WSF2         0.000000
WSF5         0.546448
dtype: float64

In [16]:
df_weather.describe()

,AWND,PGTM,PRCP,SNOW,SNWD,TAVG,TMAX,TMIN,TSUN,WDF2,WDF5,WSF2,WSF5
count,366.000000,0.0,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,0.0,366.000000,364.000000,366.000000,364.000000
mean,9.429973,NaN,0.104945,0.098087,0.342623,57.196721,65.991803,48.459016,NaN,217.841530,228.269231,20.484426,26.801648
std,3.748174,NaN,0.307496,1.276498,2.078510,17.466981,18.606301,17.135790,NaN,102.548282,97.415777,6.848390,8.882610
min,2.460000,NaN,0.000000,0.000000,0.000000,8.000000,18.000000,0.000000,NaN,10.000000,10.000000,6.900000,10.100000
25%,6.765000,NaN,0.000000,0.000000,0.000000,43.000000,51.250000,35.000000,NaN,150.000000,150.000000,15.000000,19.900000
50%,8.720000,NaN,0.000000,0.000000,0.000000,56.000000,66.000000,47.000000,NaN,240.000000,260.000000,19.900000,25.100000
75%,11.410000,NaN,0.030000,0.000000,0.000000,74.000000,83.000000,64.000000,NaN,300.000000,300.000000,23.900000,31.100000
max,22.820000,NaN,2.790000,24.000000,20.100000,89.000000,99.000000,80.000000,NaN,360.000000,360.000000,48.100000,66.000000

In [17]:
df_weather.isna()

,STATION,NAME,DATE,AWND,PGTM,PRCP,SNOW,SNWD,TAVG,TMAX,TMIN,TSUN,WDF2,WDF5,WSF2,WSF5
0,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False
1,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False
2,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False
4,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False
362,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False
363,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False
364,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False
365,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False

In [21]:
df_weather.dropna(how='all', axis=1, inplace=True)

(366, 14)

In [20]:
df_weather.shape

(366, 16)

## Trips Data

In [22]:
df_trips = load_raw_file('JC-201601-citibike-tripdata.csv')

In [23]:
df_trips.head()

,Trip Duration,Start Time,Stop Time,Start Station ID,Start Station Name,Start Station Latitude,Start Station Longitude,End Station ID,End Station Name,End Station Latitude,End Station Longitude,Bike ID,User Type,Birth Year,Gender
0,362,2016-01-01 00:02:52,2016-01-01 00:08:54,3186,Grove St PATH,40.719586,-74.043117,3209,Brunswick St,40.724176,-74.050656,24647,Subscriber,1964.0,2
1,200,2016-01-01 00:18:22,2016-01-01 00:21:42,3186,Grove St PATH,40.719586,-74.043117,3213,Van Vorst Park,40.718489,-74.047727,24605,Subscriber,1962.0,1
2,202,2016-01-01 00:18:25,2016-01-01 00:21:47,3186,Grove St PATH,40.719586,-74.043117,3213,Van Vorst Park,40.718489,-74.047727,24689,Subscriber,1962.0,2
3,248,2016-01-01 00:23:13,2016-01-01 00:27:21,3209,Brunswick St,40.724176,-74.050656,3203,Hamilton Park,40.727596,-74.044247,24693,Subscriber,1984.0,1
4,903,2016-01-01 01:03:20,2016-01-01 01:18:24,3195,Sip Ave,40.730743,-74.063784,3210,Pershing Field,40.742677,-74.051789,24573,Customer,NaN,0

In [24]:
df_trips.describe()

,Trip Duration,Start Station ID,Start Station Latitude,Start Station Longitude,End Station ID,End Station Latitude,End Station Longitude,Bike ID,Birth Year,Gender
count,7.479000e+03,7479.000000,7479.000000,7479.000000,7479.000000,7479.000000,7479.000000,7479.000000,7177.000000,7479.000000
mean,8.760840e+02,3199.060035,40.723892,-74.046672,3196.959888,40.723235,-74.045822,24545.918171,1978.285356,1.155903
std,1.877094e+04,11.158335,0.007836,0.011177,32.764969,0.007745,0.011177,176.014069,9.688657,0.462590
min,6.100000e+01,3183.000000,40.697030,-74.096937,534.000000,40.697030,-74.096937,17941.000000,1941.000000,0.000000
25%,2.360000e+02,3186.000000,40.718489,-74.050656,3186.000000,40.718489,-74.050656,24454.000000,1973.000000,1.000000
50%,3.610000e+02,3199.000000,40.723659,-74.044247,3195.000000,40.721124,-74.043845,24559.000000,1980.000000,1.000000
75%,5.780000e+02,3209.000000,40.727596,-74.036486,3209.000000,40.727596,-74.036486,24640.000000,1985.000000,1.000000
max,1.569765e+06,3225.000000,40.752559,-74.032108,3225.000000,40.752559,-74.012723,24724.000000,1998.000000,2.000000

In [26]:
df_trips.isna().sum() / df_trips.shape[0]

Trip Duration              0.00000
Start Time                 0.00000
Stop Time                  0.00000
Start Station ID           0.00000
Start Station Name         0.00000
Start Station Latitude     0.00000
Start Station Longitude    0.00000
End Station ID             0.00000
End Station Name           0.00000
End Station Latitude       0.00000
End Station Longitude      0.00000
Bike ID                    0.00000
User Type                  0.00000
Birth Year                 0.04038
Gender                     0.00000
dtype: float64